env:
  es2021: true
extends:
  - 'airbnb-base'
  - 'prettier'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - 'jest'
rules:
  {
    'no-console': 1,
    'import/no-extraneous-dependencies': ['error', { devDependencies: ['**/*.test.js'] }],
    'no-underscore-dangle': [2, { 'allow': ['__filename', '__dirname'] }],
    'no-useless-escape': 1,
  }
