#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling and testing project before committing'
npx lint-staged ||
(
        echo '😤🏀👋😤 Lint Check Failed. 😤🏀👋😤
                Make the required changes listed above, add changes and try to commit again.'
        false;
)
echo '✅✅✅✅ I am committing this now. ✅✅✅✅'
